config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


# Add this import
from .views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    # index page
    path('', home, name='home'),
    path('contact/', include('contact.urls')),
    path('auth/', include('accounts.urls')),
    path('teacher/', include('teacher.urls')),
    path('events/', include('events.urls')),
    path('courses/', include('course.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

course/urls.py
from django.urls import path

from . import views

app_name = 'course'

urlpatterns = [
    path('', views.course_list, name='course_list'),
    path('<int:course_id>/', views.course_detail, name='detail'),
    path('<int:course_id>/enroll/', views.course_enroll, name='enroll'),
    path('my-courses/', views.course_my_courses, name='my_courses'),
    path('my-courses/<int:course_id>/',
         views.course_my_course_detail, name='my_course_detail'),
    path('<int:course_id>/lesson/<int:lesson_id>/finished/',
         views.finsihed_lesson, name='finished_lesson'),
    path('<int:course_id>/lesson/<int:lesson_id>/',
         views.lesson_detail, name='lesson_detail')
]

course/models.py
from django.db import models

from teacher.models import Teacher


class Coures(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='course/images')
    teacher = models.ForeignKey(
        Teacher, on_delete=models.CASCADE, related_name='courses')
    description = models.TextField()
    price = models.IntegerField()
    duration = models.IntegerField(help_text='Duration in days')
    is_published = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.name} - {self.teacher.name}"


class CourseLesson(models.Model):
    course = models.ForeignKey(Coures, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    youtube_url = models.CharField(max_length=200)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.title} - {self.course.name}"

course/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Create your views here.
from .models import Coures, CourseLesson
from accounts.models import UserCourse, UserFinishedCourseLesson


def course_list(request):
    courses = Coures.objects.filter(is_published=True)
    return render(request, 'course/list.html', {'courses': courses})


def course_detail(request, course_id):
    course = Coures.objects.get(id=course_id)
    lessons = CourseLesson.objects.filter(course=course)
    return render(request, 'course/detail.html', {'course': course, 'lessons': lessons})


@login_required
def course_enroll(request, course_id):
    course = Coures.objects.get(id=course_id)
    user = User.objects.get(id=request.user.id)
    UserCourse.objects.get_or_create(user=user, course=course)
    messages.success(request, 'Muaffaqiyatli kursga yozildingiz!')
    return redirect('course:my_courses')


@login_required
def course_my_courses(request):
    user = User.objects.get(id=request.user.id)
    courses = UserCourse.objects.filter(user=user)
    return render(request, 'course/my_courses.html', {'courses': courses})


@login_required
def course_my_course_detail(request, course_id):
    my_course = Coures.objects.get(id=course_id)
    lessons = CourseLesson.objects.filter(course=my_course)
    # add lesson_is_finished to each lesson via a for loop
    for lesson in lessons:
        lesson.lesson_is_finished = UserFinishedCourseLesson.objects.filter(
            enrolled_course__user=request.user, enrolled_course__course=my_course, lessons=lesson).exists()

    return render(request, 'course/my_course_detail.html', {'lessons': lessons, 'my_course': my_course})


@login_required
def lesson_detail(request, course_id, lesson_id):
    course = Coures.objects.get(id=course_id)
    lesson = CourseLesson.objects.get(id=lesson_id)
    return render(request, 'course/lesson_detail.html', {'lesson': lesson, 'course': course})


@login_required
def finsihed_lesson(request, course_id, lesson_id):
    course = Coures.objects.get(id=course_id)
    lesson = CourseLesson.objects.get(id=lesson_id, course=course)
    user_course = UserCourse.objects.get(user=request.user, course=course)
    user_finished_lesson, _ = UserFinishedCourseLesson.objects.get_or_create(
        enrolled_course=user_course)
    user_finished_lesson.lessons.add(lesson)
    user_finished_lesson.save()
    messages.success(request, 'Dars muvaffaqiyatli tugallandi!')
    return redirect('course:my_course_detail', course_id=course_id)

templates/course/detail.html
{% extends 'base/base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
<!-- page title -->
<section class="page-title-section overlay" data-background="{% static 'images/backgrounds/page-title.jpg' %}">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <ul class="list-inline custom-breadcrumb">
                    <li class="list-inline-item"><a class="h2 text-primary font-secondary" href="#">Kurslarimiz</a></li>
                    <li class="list-inline-item text-white h3 font-secondary nasted">
                        {{ course.name }}
                    </li>
                </ul>
                <!-- <p class="text-lighten">Kurslarimiz</p> -->
            </div>
        </div>
    </div>
</section>
<!-- /page title -->

<!-- section -->
<section class="section-sm">
    <div class="container">
        <div class="row">
            <div class="col-12 mb-4">
                <!-- course thumb -->
                <img src="{{ course.image.url }}" class="img-fluid w-100" alt="course thumb">
            </div>
        </div>
        <!-- course info -->
        <div class="row align-items-center mb-5">
            <div class="col-xl-3 order-1 col-sm-6 mb-4 mb-xl-0">
                <h2>{{course.name}}</h2>
            </div>
            <div class="col-xl-6 order-sm-3 order-xl-2 col-12 order-2">
                <ul class="list-inline text-xl-center">
                    <li class="list-inline-item mr-4 mb-3 mb-sm-0">
                        <div class="d-flex align-items-center">
                            <i class="ti-book text-primary icon-md mr-2"></i>
                            <div class="text-left">
                                <h6 class="mb-0">Muddati</h6>
                                <p class="mb-0">{{course.duration}} kun</p>
                            </div>
                        </div>
                    </li>

                    <li class="list-inline-item mr-4 mb-3 mb-sm-0">
                        <div class="d-flex align-items-center">
                            <i class="ti-wallet text-primary icon-md mr-2"></i>
                            <div class="text-left">
                                <h6 class="mb-0">Narx</h6>
                                <p class="mb-0">{{course.price}} so'm</p>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="col-xl-3 text-sm-right text-left order-sm-2 order-3 order-xl-3 col-sm-6 mb-4 mb-xl-0">
                <a href="{% url 'course:enroll' course.id %}" class="btn btn-primary">
                    Kursga yozilish
                </a>
            </div>
            <!-- border -->
            <div class="col-12 mt-4 order-4">
                <div class="border-bottom border-primary"></div>
            </div>
        </div>
        <!-- course details -->
        <div class="row">
            <div class="col-12 mb-4">
                <h3>Kurs haqida</h3>
                <p>
                    {{course.description}}
                </p>
            </div>
            <div class="col-12 mb-4">
                <h3 class="mb-3">Darslar ro'yxati</h3>
                <ul class="list-styled">
                    {% for lesson in lessons %}
                    <li>
                        <h6>{{lesson.title}}</h6>
                        <p>{{lesson.description|slice:":100"}}</p>
                    </li>
                    {% empty %}
                    <li>
                        <h6>
                            <a href="#">
                                Darslar mavjud emas.
                            </a>
                        </h6>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            <!-- teacher -->
            <div class="col-12">
                <h5 class="mb-3">
                    Muallif
                </h5>
                <div class="d-flex justify-content-between align-items-center flex-wrap">
                    <div class="media mb-2 mb-sm-0">
                        <img class="mr-4 img-fluid" src="{{ course.teacher.profile_pic.url }}" alt="teacher"
                            style="width: 100px; height: 100px;">
                        <div class=" media-body">
                            <h4 class="mt-0">
                                {% if course.teacher %}
                                {{course.teacher.name}}
                                {% else %}
                                Muallif mavjud emas.
                                {% endif %}
                            </h4>
                            {{course.teacher.job_title}}
                        </div>
                    </div>
                    <div class="social-link">
                        <h6 class="d-none d-sm-block">
                            Ijtimoiy tarmoqlar
                        </h6>
                        <ul class="list-inline">
                            <li class="list-inline-item"><a class="text-color" href=mailto:"{{ course.teacher.email }}">
                                    <i class="ti-email"></i>
                                </a>
                            </li>

                            <li class="list-inline-item"><a class="text-color" href="tel:{{ course.teacher.phone }}">
                                    <i class="ti-agenda"></i>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="border-bottom border-primary mt-4"></div>
            </div>
        </div>
    </div>
</section>
<!-- /section -->

<!-- related course -->
{% comment %}
<section class="section pt-0">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <h2 class="section-title">Related Course</h2>
            </div>
        </div>
        <div class="row justify-content-center">
            <!-- course item -->
            <div class="col-lg-4 col-sm-6 mb-5">
                <div class="card p-0 border-primary rounded-0 hover-shadow">
                    <img class="card-img-top rounded-0" src="images/courses/course-1.jpg" alt="course thumb">
                    <div class="card-body">
                        <ul class="list-inline mb-2">
                            <li class="list-inline-item"><i class="ti-calendar mr-1 text-color"></i>02-14-2018</li>
                            <li class="list-inline-item"><a class="text-color" href="#">Humanities</a></li>
                        </ul>
                        <a href="#">
                            <h4 class="card-title">
                                {{ course.name }}
                            </h4>
                        </a>
                        <p class="card-text mb-4"> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
                            eiusmod tempor
                            incididunt ut labore et dolore magna.</p>
                        <a href="#" class="btn btn-primary btn-sm">Apply now</a>
                    </div>
                </div>
            </div>
            <!-- course item -->
            <div class="col-lg-4 col-sm-6 mb-5">
                <div class="card p-0 border-primary rounded-0 hover-shadow">
                    <img class="card-img-top rounded-0" src="images/courses/course-2.jpg" alt="course thumb">
                    <div class="card-body">
                        <ul class="list-inline mb-2">
                            <li class="list-inline-item"><i class="ti-calendar mr-1 text-color"></i>02-14-2018</li>
                            <li class="list-inline-item"><a class="text-color" href="#">Humanities</a></li>
                        </ul>
                        <a href="course-single.html">
                            <h4 class="card-title">Programming</h4>
                        </a>
                        <p class="card-text mb-4"> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
                            eiusmod tempor
                            incididunt ut labore et dolore magna.</p>
                        <a href="course-single.html" class="btn btn-primary btn-sm">Apply now</a>
                    </div>
                </div>
            </div>
            <!-- course item -->
            <div class="col-lg-4 col-sm-6 mb-5">
                <div class="card p-0 border-primary rounded-0 hover-shadow">
                    <img class="card-img-top rounded-0" src="images/courses/course-3.jpg" alt="course thumb">
                    <div class="card-body">
                        <ul class="list-inline mb-2">
                            <li class="list-inline-item"><i class="ti-calendar mr-1 text-color"></i>02-14-2018</li>
                            <li class="list-inline-item"><a class="text-color" href="#">Humanities</a></li>
                        </ul>
                        <a href="course-single.html">
                            <h4 class="card-title">Lifestyle Archives</h4>
                        </a>
                        <p class="card-text mb-4"> Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do
                            eiusmod tempor
                            incididunt ut labore et dolore magna.</p>
                        <a href="course-single.html" class="btn btn-primary btn-sm">Apply now</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endcomment %}
<!-- /related course -->
{% endblock %}

templates/course/lesson_detail.html
{% extends 'base/base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
<!-- page title -->
<section class="page-title-section overlay" data-background="{% static 'images/backgrounds/page-title.jpg' %}">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <ul class="list-inline custom-breadcrumb">
                    <li class="list-inline-item"><a class="h2 text-primary font-secondary" href="#">
                            {{ course.name }}
                        </a></li>
                    <li class="list-inline-item text-white h3 font-secondary nasted">
                        {{ lesson.title }}
                    </li>
                </ul>
                <!-- <p class="text-lighten">My courses lesson</p> -->
            </div>
        </div>
    </div>
</section>
<!-- /page title -->

<!-- section -->
<section class="section-sm">
    <div class="container">
        <div class="row">
            <div class="col-12 mb-4">
                <!-- course thumb -->
                <iframe width="1200" height="600" src="https://www.youtube.com/embed/{{ lesson.youtube_url }}"
                    title="YouTube video player" frameborder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                    referrerpolicy="strict-origin-when-cross-origin" allowfullscreen>
                </iframe>
            </div>
        </div>
        <!-- course info -->
        <div class="row align-items-center mb-5">
            <div class="col-xl-3 order-1 col-sm-6 mb-4 mb-xl-0">
                <h2>{{lesson.title}}</h2>
            </div>

            <div class="col-xl-3 text-sm-right text-left order-sm-2 order-3 order-xl-3 col-sm-6 mb-4 mb-xl-0">
                <a href="{% url 'course:finished_lesson' course.id lesson.id %}" class="btn btn-success">
                    Tugatish
                    <i class="ti ti-check"></i>
                </a>
            </div>
            <!-- border -->
            <div class="col-12 mt-4 order-4">
                <div class="border-bottom border-primary"></div>
            </div>
        </div>
        <div class="row">
            <div class="col-12 mb-4">
                <h3>Dars haqida</h3>
                <p>
                    {{lesson.description}}
                </p>
            </div>
        </div>

    </div>
</section>
<!-- /section -->

{% endblock %}

templates/course/list.html
{% extends 'base/base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
<!-- page title -->
<section class="page-title-section overlay" data-background="{% static 'images/backgrounds/page-title.jpg' %}">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <ul class="list-inline custom-breadcrumb">
                    <li class="list-inline-item"><a class="h2 text-primary font-secondary" href="#">Kurslarimiz</a></li>
                    <li class="list-inline-item text-white h3 font-secondary "></li>
                </ul>
                <p class="text-lighten">Kurslarimiz</p>
            </div>
        </div>
    </div>
</section>
<!-- /page title -->

<!-- courses -->
<section class="section">
    <div class="container">
        <!-- course list -->
        <div class="row justify-content-center">

            <!-- course item -->
            {% for course in courses %}
            <div class="col-lg-4 col-sm-6 mb-5">
                <div class="card p-0 border-primary rounded-0 hover-shadow">
                    <img class="card-img-top rounded-0" src="{{ course.image.url }}" alt="course thumb">
                    <div class="card-body">
                        <ul class="list-inline mb-2">
                            <li class="list-inline-item">
                                <i class="ti-calendar mr-1 text-color"></i>
                                {{ course.created_at|date:"d M, Y" }}
                            </li>
                        </ul>
                        <a href="{% url 'course:detail' course.id %}">
                            <h4 class="card-title">{{ course.name }}</h4>
                        </a>
                        <p class="card-text mb-4">
                            {{ course.description|slice:":100" }}
                        </p>
                        <a href="{% url 'course:detail' course.id %}" class="btn btn-primary btn-sm">
                            Kursga o'tish
                        </a>
                    </div>
                </div>
            </div>
            {% endfor %}

        </div>
        <!-- /course list -->

    </div>
</section>
<!-- /courses -->

{% endblock %}

templates/course/my_course_detail.html
{% extends 'base/base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
<!-- page title -->
<section class="page-title-section overlay" data-background="{% static 'images/backgrounds/page-title.jpg' %}">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <ul class="list-inline custom-breadcrumb">
                    <li class="list-inline-item"><a class="h2 text-primary font-secondary" href="#">
                            Mening kurslarim
                        </a></li>
                    <li class="list-inline-item text-white h3 font-secondary nasted">
                        {{ my_course.name }}
                    </li>
                </ul>
                <!-- <p class="text-lighten">
                    Mening kurslarim
                </p> -->
            </div>
        </div>
    </div>
</section>
<!-- /page title -->

<!-- section -->
<section class="section-sm">
    <div class="container">

        <!-- course info -->
        <div class="row align-items-center mb-5">
            <div class="col-xl-3 order-1 col-sm-6 mb-4 mb-xl-0">
                <h3>{{my_course.name}}</h3>
            </div>
            <!-- border -->
            <div class="col-12 mt-4 order-4">
                <div class="border-bottom border-primary"></div>
            </div>
        </div>
        <!-- course details -->
        <div class="row">
            <div class="col-12 mb-4">
                <h4 class="mb-3">Darslar</h4>
                <ul class="list-styled">
                    {% for lesson in lessons %}
                    <li>
                        <h6>
                            <a href="{% url 'course:lesson_detail' my_course.id  lesson.id %}">
                                {{lesson.title}}
                            </a>
                        </h6>
                        <p>{{lesson.description|slice:":100"}}</p>
                    </li>
                    {% empty %}
                    <li>
                        <h6>
                            <a href="#">
                                No lessons found.
                            </a>
                        </h6>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</section>
<!-- /section -->


{% endblock %}

templates/course/my_courses.html
{% extends 'base/base.html' %}
{% load static %}
{% load humanize %}

{% block content %}
<!-- page title -->
<section class="page-title-section overlay" data-background="{% static 'images/backgrounds/page-title.jpg' %}">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <ul class="list-inline custom-breadcrumb">
                    <li class="list-inline-item"><a class="h2 text-primary font-secondary" href="#">My
                            Courses</a></li>
                    <li class="list-inline-item text-white h3 font-secondary "></li>
                </ul>
                <p class="text-lighten">Kurslarimiz</p>
            </div>
        </div>
    </div>
</section>
<!-- /page title -->

<!-- courses -->
<section class="section">
    <div class="container">
        <!-- course list -->
        <div class="row justify-content-center">

            <!-- course item -->
            {% for my_course in courses %}
            <div class="col-lg-4 col-sm-6 mb-5">
                <div class="card p-0 border-primary rounded-0 hover-shadow">
                    <img class="card-img-top rounded-0" src="{{ my_course.course.image.url }}" alt="course thumb">
                    <div class="card-body">
                        <ul class="list-inline mb-2">
                            <li class="list-inline-item">
                                <i class="ti-calendar mr-1 text-color"></i>
                                {{ my_course.course.created_at|date:"d M, Y" }}
                            </li>
                        </ul>
                        <a href="{% url 'course:detail' my_course.course.id %}">
                            <h4 class="card-title">{{ my_course.course.name }}</h4>
                        </a>
                        <p class="card-text mb-4">
                            {{ my_course.course.description|slice:":100" }}
                        </p>
                        <a href="{% url 'course:my_course_detail' my_course.course.id %}"
                            class="btn btn-primary btn-sm">
                            Kursni boshlash
                        </a>
                    </div>
                </div>
            </div>
            {% empty %}
            <div class="col-12">
                <h2 class="text-center">No Courses Found</h2>
            </div>

            {% endfor %}

        </div>
        <!-- /course list -->

    </div>
</section>
<!-- /courses -->

{% endblock %}