config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


# Add this import
from .views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    # index page
    path('', home, name='home'),
    path('contact/', include('contact.urls')),
    path('auth/', include('accounts.urls')),
    path('teacher/', include('teacher.urls')),
    path('events/', include('events.urls')),
    path('courses/', include('course.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

course/urls.py
from django.urls import path

from . import views

app_name = 'course'

urlpatterns = [
    path('', views.course_list, name='course_list'),
    path('<int:course_id>/', views.course_detail, name='detail'),
    path('<int:course_id>/enroll/', views.course_enroll, name='enroll'),
    path('my-courses/', views.course_my_courses, name='my_courses'),
    path('my-courses/<int:course_id>/',
         views.course_my_course_detail, name='my_course_detail'),
    path('<int:course_id>/lesson/<int:lesson_id>/finished/',
         views.finsihed_lesson, name='finished_lesson'),
    path('<int:course_id>/lesson/<int:lesson_id>/',
         views.lesson_detail, name='lesson_detail')
]

templates/base/auth.html
{% load static %}

<!-- Modal -->
<div class="modal fade" id="signupModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content rounded-0 border-0 p-4">
            <div class="modal-header border-0">
                <h3>Register</h3>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="login">
                    <form action="{% url 'register' %}" method="post" class="row">
                        {% csrf_token %}
                        <div class="col-12">
                            <input type="email" class="form-control mb-3" id="signupEmail" name="email"
                                placeholder="Email">
                        </div>

                        <div class="col-12">
                            <input type="text" class="form-control mb-3" id="signupName" name="username"
                                placeholder="Username">
                        </div>

                        <div class="col-12">
                            <input type="password" class="form-control mb-3" id="signupPassword" name="password"
                                placeholder="Parol">
                        </div>

                        <div class="col-12">
                            <button type="submit" class="btn btn-primary">SIGN UP</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content rounded-0 border-0 p-4">
            <div class="modal-header border-0">
                <h3>Login</h3>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{% url 'login' %}" method="post" class="row">
                    {% csrf_token %}
                    <div class="col-12">
                        <input type="text" class="form-control mb-3" id="loginName" name="username"
                            placeholder="Username">
                    </div>
                    <div class="col-12">
                        <input type="password" class="form-control mb-3" id="loginPassword" name="password"
                            placeholder="Parol">
                    </div>
                    <div class="col-12">
                        <button type="submit" class="btn btn-primary">Kirish</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

templates/base/base.html
{% load static %}
{% load humanize %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>PYTHON ACADEMY</title>

    <!-- mobile responsive meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <!-- ** Plugins Needed for the Project ** -->
    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static 'plugins/bootstrap/bootstrap.min.css' %}">
    <!-- slick slider -->
    <link rel="stylesheet" href="{% static 'plugins/slick/slick.css' %}">
    <!-- themefy-icon -->
    <link rel="stylesheet" href="{% static 'plugins/themify-icons/themify-icons.css' %}">
    <!-- animation css -->
    <link rel="stylesheet" href="{% static 'plugins/animate/animate.css' %}">
    <!-- aos -->
    <link rel="stylesheet" href="{% static 'plugins/aos/aos.css' %}">
    <!-- venobox popup -->
    <link rel="stylesheet" href="{% static 'plugins/venobox/venobox.css' %}">

    <!-- Main Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <!--Favicon-->
    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'images/favicon.png' %}" type="image/x-icon">

</head>

<body>
    <!-- preloader start -->
    <div class="preloader">
        <img src="{% static 'images/preloader.gif' %}" alt="preloader">
    </div>
    <!-- preloader end -->

    <!-- header -->
    {% block header %}
    {% include 'base/header.html' %}
    {% endblock header %}
    <!-- header end -->

    <!-- auth -->
    {% block auth %}
    {% include 'base/auth.html' %}
    {% endblock auth %}

    <!-- Content Wrapper. Contains page content -->
    {% block content %}

    {% endblock content %}
    <!-- /.content-wrapper -->

    <!-- footer -->
    {% block footer %}
    {% include 'base/footer.html' %}
    {% endblock footer %}
    <!-- footer end -->

    <!-- ** js ** -->
    {% block js %}
    {% include 'base/js.html' %}
    {% endblock js %}
    <!-- ** js ** -->


</body>

</html>

templates/base/footer.html
{% load static %}

<!-- footer -->
<footer>

    <!-- footer content -->
    <div class="footer bg-footer section border-bottom" style="padding-top: 100px;">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-sm-8 mb-5 mb-lg-0">
                    <!-- logo -->
                    <h1 class="logo-footer it-pro-2" href="#"><strong class="it">PYTHON</strong> ACADEMY</h1>
                    <ul class="list-unstyled">
                        <li class="mb-2">+998 (99) 753 39 09</li>
                        <li class="mb-2">Toshkent shahar, Chilonzor tumani, Cho'pon ota ko'chasi 14/1-uy</li>
                    </ul>
                </div>
                <!-- company -->
                <div class="col-lg-2 col-md-3 col-sm-4 col-6 mb-5 mb-md-0">

                </div>
                <!-- links -->
                <div class="col-lg-2 col-md-3 col-sm-4 col-6 mb-5 mb-md-0">
                    <h4 class="text-white mb-5">Platforma</h4>
                    <ul class="list-unstyled">
                        <li class="mb-3"><a class="text-color" href="{% url 'course:course_list' %}">Kurslar</a></li>
                    </ul>
                </div>
                <!-- support -->
                <div class="col-lg-2 col-md-3 col-sm-4 col-6 mb-5 mb-md-0">
                    <h4 class="text-white mb-5">Kompaniya</h4>
                    <ul class="list-unstyled">
                        <li class="mb-3"><a class="text-color" href="#about">Biz haqimizda</a></li>
                        <li class="mb-3"><a class="text-color" href="{% static 'pdf/oferta.pdf' %}" target="_blank">
                                Ommaviy oferta
                            </a></li>
                        <li class="mb-3"><a class="text-color" href="{% static 'pdf/privacy_policy.pdf' %}"
                                target="_blank">
                                Maxfiylik siyosati
                            </a></li>
                    </ul>
                </div>
                <!-- support -->
                <div class="col-lg-2 col-md-3 col-sm-4 col-6 mb-5 mb-md-0">
                    <h4 class="text-white mb-5">Ma'lumot</h4>
                    <ul class="list-unstyled">
                        <li class="mb-3"><a class="text-color" href="{% url 'contact' %}">Bog'lanish</a></li>
                        <li class="mb-3"><a class="text-color" href="{% static 'pdf/guvohnoma.pdf' %}" target="_blank">`
                                Guvohnoma
                            </a></li>
                        <li class="mb-3"><a class="text-color" href="#">
                                Fikrlar
                            </a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- /footer -->

templates/base/header.html
{% load static %}

<!-- header -->
<header class="fixed-top header">
    <!-- top header -->
    <div class="top-header py-2 bg-white">
        <div class="container">
            <div class="row no-gutters">
                <div class="col-lg-12 text-center text-lg-center">
                    {% if messages %}
                    {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    {% endfor %}
                    {% endif %}
                </div>
                <div class="col-lg-4 text-center text-lg-left">

                    <a class="text-color mr-3" href="callto:+443003030266"><strong>Tel</strong> +998 99 753 39 09</a>
                    <ul class="list-inline d-inline">
                        <li class="list-inline-item mx-0"><a class="d-inline-block p-2 text-color" href="#"><i
                                    class="ti-facebook"></i></a></li>
                        <li class="list-inline-item mx-0"><a class="d-inline-block p-2 text-color" href="#"><i
                                    class="ti-twitter-alt"></i></a></li>
                        <li class="list-inline-item mx-0"><a class="d-inline-block p-2 text-color" href="#"><i
                                    class="ti-linkedin"></i></a></li>
                        <li class="list-inline-item mx-0"><a class="d-inline-block p-2 text-color" href="#"><i
                                    class="ti-instagram"></i></a></li>
                    </ul>
                </div>
                <div class="col-lg-8 text-center text-lg-right">
                    <ul class="list-inline">
                        {% if user.is_authenticated %}
                        <li class="list-inline-item"><a
                                class="text-uppercase text-color p-sm-2 py-2 px-0 d-inline-block"
                                href="{% url 'logout' %}">Chiqish</a>
                        </li>
                        <li class="list-inline-item"><a
                                class="text-uppercase text-color p-sm-2 py-2 px-0 d-inline-block"
                                href="{% url 'course:my_courses' %}">Mening kurslarim</a>
                        </li>
                        {% else %}
                        <li class="list-inline-item"><a
                                class="text-uppercase text-color p-sm-2 py-2 px-0 d-inline-block" href="#"
                                data-toggle="modal" data-target="#loginModal">Kirish</a></li>
                        <li class="list-inline-item"><a
                                class="text-uppercase text-color p-sm-2 py-2 px-0 d-inline-block" href="#"
                                data-toggle="modal" data-target="#signupModal">Registratsiya</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- navbar -->
    <div class="navigation w-100">
        <div class="container">
            <nav class="navbar navbar-expand-lg navbar-dark p-0">
                <h1 class="navbar-brand it-pro" href="#"><strong class="it">PYTHON</strong> ACADEMY</h1>
                <button class="navbar-toggler rounded-0" type="button" data-toggle="collapse" data-target="#navigation"
                    aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navigation">
                    <ul class="navbar-nav ml-auto text-center">
                        <li class="nav-item">
                            <a class="nav-link" href="/">Asosiy</a>
                        </li>
                        <li class="nav-item @@courses">
                            <a class="nav-link" href="{% url 'course:course_list' %}">Kurslar</a>
                        </li>
                        <li class="nav-item @@events">
                            <a class="nav-link" href="{% url 'event_list' %}">Yangiliklar</a>
                        </li>
                        <li class="nav-item @@teacher">
                            <a class="nav-link" href="{% url 'teacher_list' %}">
                                O'qituvchilar
                            </a>
                        </li>
                        <li class="nav-item @@contact">
                            <a class="nav-link" href="{% url 'contact' %}">Bog'lanish
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
        </div>
    </div>
</header>
<!-- /header -->

templates/base/js.html
{% load static %}

<!-- jQuery -->
<script src="{% static 'plugins/jQuery/jquery.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'plugins/bootstrap/bootstrap.min.js' %}"></script>
<!-- slick slider -->
<script src="{% static 'plugins/slick/slick.min.js' %}"></script>
<!-- aos -->
<script src="{% static 'plugins/aos/aos.js' %}"></script>
<!-- venobox popup -->
<script src="{% static 'plugins/venobox/venobox.min.js' %}"></script>
<!-- filter -->
<script src="{% static 'plugins/filterizr/jquery.filterizr.min.js' %}"></script>
<!-- google map -->
<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY"></script>
<script src="{% static 'plugins/google-map/gmap.js' %}"></script>

<!-- Main Script -->
<script src="{% static 'js/script.js' %}"></script>